site_name: Hướng dẫn sử dụng Pisale
site_description: Trang tài liệu hướng dẫn sử dụng sản phẩm bán lẻ Pisale
site_url: https://pisale-doc.osd.vn

theme:
  name: material
  custom_dir: overrides/
  language: en
  
extra_css:
  - styles/custom.css
  
nav:
  - Bắt đầu: index.md
  - Tính năng chung:
    - Trình quản lý tệp (Finder): common/finder.md
    - Câu hỏi thường gặp: common/faqs.md

plugins:
  - glightbox:
      touchNavigation: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  generator: false
  
copyright: Copyright &copy; 2012 - 2026 OSD.VN
