site_name: TÃ i liá»‡u hÆ°á»›ng dáº«n sá»­ dá»¥ng
site_description: Há»‡ thá»‘ng tÃ i liá»‡u hÆ°á»›ng dáº«n sá»­ dá»¥ng dá»‹ch vá»¥ vÃ  sáº£n pháº©m
site_url: https://kb.osd.vn

theme:
  name: shadcn
  show_title: true
  show_stargazers: true
  pygments_style:
    light: shadcn-light
    dark: github-dark

nav:
  - Trang chá»§: index.md
  - Guide: guide.md
  - Private Docs ðŸ”’:
      - Overview: private/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  generator: false
