site_name: Hướng dẫn sử dụng Pisale
site_description: Trang tài liệu hướng dẫn sử dụng sản phẩm bán lẻ Pisale
site_url: https://pisale-doc.osd.vn

theme:
  name: material
  custom_dir: overrides/
  language: vi
  
features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    
nav:
  - Bắt đầu: index.md
  - Tính năng chung:
    - Quản lý tệp (Finder): common/finder.md
    - Câu hỏi thường gặp: common/faqs.md
    - Các logic: common/logic.md
    - Trình soạn thảo nội dung: common/tinymce
    - Mục lục tự động: common/toc
  - Quản lý nội dung:
    - Đặc tính sản phẩm: catalog/attribute
    - Nhóm đặc tính: catalog/attribute_group
    - Nhóm sản phẩm: catalog/category
    - Thư viện ảnh: catalog/gallery
    - Longform: catalog/gridpage
    - Thông tin: catalog/information
    - Nhà sản xuất: catalog/manufacturer
    - Tin bài: catalog/news
    - Chuyên mục tin bài: catalog/news_category
    - Tuỳ chọn: catalog/option
    - Dự án tiêu biểu: catalog/portfolio
    - Sản phẩm: catalog/product
    - Dịch vụ: catalog/service
    - Nhóm dịch vụ: catalog/service_cat
  - Giao diện:
    - Mô đun:
      - Banner: design/module/banner
      - Nhóm sản phẩm: design/module/category
      - Facebook Business Page: design/module/facebook_lb
      - Grid Content: design/module/grid
      - Danh sách nhà sản xuất: design/module/manufacturer
      - Trình bày tin bài: design/module/news
      - Chuyên mục tin: design/module/news_category
      - Trình bày sản phẩm: design/module/product_category
      - Hộp tìm kiếm: design/module/searchbox
      - Mạng xã hội: design/module/social
      - Hệ thống cửa hàng: design/module/store
      - Hỗ trợ trực tuyến: design/module/supportonline
      - Nội dung: design/module/welcome
    - Banner & trình diễn: design/banner
    - Mã nhúng: design/custom
    - Nhận diện: design/display
    - Trình đơn & trình bày trình đơn: design/menumanager
  - SEO:
    - Cấu hình chung: seo/seo
    - Chuyển hướng URL: seo/redirect
  - Hệ thống:
    - Tích hợp: setting/intergrate
    - Thành viên:
      - Thành viên: setting/user/user
      - Vai trò: setting/user/user_permission
    - Quản lý Mẫu nội dung: setting/pattern
    - Thiết lập hệ thống: setting/setting
    - Chi nhánh, cơ sở kinh doanh: setting/store

plugins:

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

extra:
  generator: false
  
copyright: Copyright &copy; 2012 - 2026 OSD.VN
